// Generated by CoffeeScript 1.8.0
(function() {
  var apiURL, boletimApp;

  apiURL = 'http://api.servidor.adv.br/crsr/api/v.1';

  boletimApp = angular.module('boletimApp', ['ngSanitize', 'ngRoute', 'cgBusy']);

  boletimApp.service('boletimService', function($http) {
    delete $http.defaults.headers.common['X-Requested-With'];
    this.obterBoletims = function(limit, offset) {
      return $http({
        method: 'GET',
        url: apiURL + '/boletim/?sort_by=datadepublicacao&sort_desc=true&limit=' + limit + '&offset=' + offset
      });
    };
    this.obterBoletim = function(boletimId) {
      return $http({
        method: 'GET',
        url: apiURL + '/boletim/' + boletimId
      });
    };
  });

  boletimApp.controller('BoletimController', function($scope, $routeParams, boletimService) {
    $scope.offset = 0;
    $scope.limit = 10;
    $scope.boletins = [];
    $scope.ultimasBoletins = [];
    if ($routeParams.boletimId != null) {
      $scope.listaPrincipalPromise = boletimService.obterBoletim($routeParams.boletimId);
      $scope.listaPrincipalPromise.then(function(dataResponse) {
        return $scope.boletins[0] = dataResponse.data;
      });
    } else {
      $scope.listaPrincipalPromise = boletimService.obterBoletims($scope.limit, $scope.offset);
      $scope.listaPrincipalPromise.then(function(dataResponse) {
        return $scope.boletins = dataResponse.data;
      });
    }
    $scope.noticiaLateralPromise = boletimService.obterBoletims(15, 0);
    $scope.noticiaLateralPromise.then(function(dataResponse) {
      return $scope.ultimasBoletins = dataResponse.data;
    });
    $scope.url = function(boletim) {
      return boletim.titulo.toLowerCase().replace(/\ /g, '-').replace(/[^\w-]+/g, "") + '/' + boletim.id;
    };
    $scope.urltwitter = function(boletim) {
      var title;
      title = '';
      if ($routeParams.boletimId == null) {
        title = "/" + boletim.titulo.toLowerCase().replace(/\ /g, '-').replace(/[^\w-]+/g, "") + '/' + boletim.id;
      }
      return "http://platform.twitter.com/widgets/tweet_button.ff7d9077a26377d36b6a53b1a95be617.en.html#_=1418920477717&count=horizontal&id=twitter-widget-0&lang=en&original_referer=" + encodeURIComponent(window.location.href) + "&size=m&text=@ceradvogados:&url=" + encodeURIComponent(window.location.href + title);
    };
    $scope.urlfacebook = function(boletim) {
      var title;
      title = '';
      if ($routeParams.boletimId == null) {
        title = "/" + boletim.titulo.toLowerCase().replace(/\ /g, '-').replace(/[^\w-]+/g, "") + '/' + boletim.id;
      }
      return "http://www.facebook.com/plugins/like.php?href=" + encodeURIComponent(window.location.href + title) + "&layout=button_count&show_faces=false&width=90&action=like&font=verdana&colorscheme=light&locale=pt_BR";
    };
    $scope.urlgoogle = function(boletim) {
      var title;
      title = '';
      if ($routeParams.boletimId == null) {
        title = "/" + boletim.titulo.toLowerCase().replace(/\ /g, '-').replace(/[^\w-]+/g, "") + '/' + boletim.id;
      }
      return "https://plusone.google.com/_/+1/fastbutton?bsv&size=medium&hl=en-US&url=" + window.location.href + title + "&parent=" + window.location.href;
    };
  });

  boletimApp.config(function($sceProvider) {
    return $sceProvider.enabled(false);
  });

  boletimApp.config(function($routeProvider, $locationProvider) {
    $routeProvider.when('/boletim', {
      templateUrl: 'boletim_partial_listagem.html',
      controller: 'BoletimController'
    }).when('/boletim/:title/:boletimId', {
      templateUrl: 'boletim_partial_listagem.html',
      controller: 'BoletimController'
    }).otherwise({
      redirectTo: '/boletim'
    });
    return $locationProvider.html5Mode(true);
  });

  boletimApp.value('cgBusyDefaults', {
    message: 'Carregando',
    backdrop: false,
    templateUrl: 'loader_template.html',
    delay: 500
  });

}).call(this);
