// Generated by CoffeeScript 1.8.0
(function() {
  var apiURL, clippingApp;

  apiURL = 'http://api.servidor.adv.br/crsr/api/v.1';

  clippingApp = angular.module('clippingApp', ['ngSanitize', 'ngRoute', 'cgBusy']);

  clippingApp.service('clippingService', function($http) {
    delete $http.defaults.headers.common['X-Requested-With'];
    this.obterClippings = function(limit, offset) {
      return $http({
        method: 'GET',
        url: apiURL + '/clipping/?sort_by=datapublicacao&sort_desc=true&limit=' + limit + '&offset=' + offset
      });
    };
    this.obterClipping = function(clippingId) {
      return $http({
        method: 'GET',
        url: apiURL + '/clipping/' + clippingId
      });
    };
  });

  clippingApp.controller('ClippingController', function($scope, $routeParams, clippingService) {
    $scope.offset = 0;
    $scope.limit = 10;
    $scope.clippings = [];
    $scope.ultimasClippings = [];
    if ($routeParams.clippingId != null) {
      $scope.listaPrincipalPromise = clippingService.obterClipping($routeParams.clippingId);
      $scope.listaPrincipalPromise.then(function(dataResponse) {
        return $scope.clippings[0] = dataResponse.data;
      });
    } else {
      $scope.listaPrincipalPromise = clippingService.obterClippings($scope.limit, $scope.offset);
      $scope.listaPrincipalPromise.then(function(dataResponse) {
        return $scope.clippings = dataResponse.data;
      });
    }
    $scope.noticiaLateralPromise = clippingService.obterClippings(15, 0);
    $scope.noticiaLateralPromise.then(function(dataResponse) {
      return $scope.ultimasClippings = dataResponse.data;
    });
    $scope.url = function(clipping) {
      return clipping.titulo.toLowerCase().replace(/\ /g, '-').replace(/[^\w-]+/g, "") + '/' + clipping.id;
    };
    $scope.urltwitter = function(clipping) {
      var title;
      title = '';
      if ($routeParams.clippingId == null) {
        title = "/" + clipping.titulo.toLowerCase().replace(/\ /g, '-').replace(/[^\w-]+/g, "") + '/' + clipping.id;
      }
      return "http://platform.twitter.com/widgets/tweet_button.ff7d9077a26377d36b6a53b1a95be617.en.html#_=1418920477717&count=horizontal&id=twitter-widget-0&lang=en&original_referer=" + encodeURIComponent(window.location.href) + "&size=m&text=@ceradvogados:&url=" + encodeURIComponent(window.location.href + title);
    };
    $scope.urlfacebook = function(clipping) {
      var title;
      title = '';
      if ($routeParams.clippingId == null) {
        title = "/" + clipping.titulo.toLowerCase().replace(/\ /g, '-').replace(/[^\w-]+/g, "") + '/' + clipping.id;
      }
      return "http://www.facebook.com/plugins/like.php?href=" + encodeURIComponent(window.location.href + title) + "&layout=button_count&show_faces=false&width=90&action=like&font=verdana&colorscheme=light&locale=pt_BR";
    };
    $scope.urlgoogle = function(clipping) {
      var title;
      title = '';
      if ($routeParams.clippingId == null) {
        title = "/" + clipping.titulo.toLowerCase().replace(/\ /g, '-').replace(/[^\w-]+/g, "") + '/' + clipping.id;
      }
      return "https://plusone.google.com/_/+1/fastbutton?bsv&size=medium&hl=en-US&url=" + window.location.href + title + "&parent=" + window.location.href;
    };
  });

  clippingApp.config(function($sceProvider) {
    return $sceProvider.enabled(false);
  });

  clippingApp.config(function($routeProvider, $locationProvider) {
    $routeProvider.when('/clipping', {
      templateUrl: 'clipping_partial_listagem.html',
      controller: 'ClippingController'
    }).when('/clipping/:title/:clippingId', {
      templateUrl: 'clipping_partial_listagem.html',
      controller: 'ClippingController'
    }).otherwise({
      redirectTo: '/clipping'
    });
    return $locationProvider.html5Mode(true);
  });

  clippingApp.value('cgBusyDefaults', {
    message: 'Carregando',
    backdrop: false,
    templateUrl: 'loader_template.html',
    delay: 500
  });

}).call(this);
