// Generated by CoffeeScript 1.8.0
(function() {
  var apiURL, naMidiaApp;

  apiURL = 'http://api.servidor.adv.br/crsr/api/v.1';

  naMidiaApp = angular.module('naMidiaApp', ['ngSanitize', 'ngRoute', 'cgBusy']);

  naMidiaApp.service('naMidiaService', function($http) {
    delete $http.defaults.headers.common['X-Requested-With'];
    this.obterNaMidias = function(limit, offset) {
      return $http({
        method: 'GET',
        url: apiURL + '/na_midia/?sort_by=datapublicacao&sort_desc=true&limit=' + limit + '&offset=' + offset
      });
    };
    this.obterNaMidia = function(naMidiaId) {
      return $http({
        method: 'GET',
        url: apiURL + '/na_midia/' + naMidiaId
      });
    };
  });

  naMidiaApp.controller('NaMidiaController', function($scope, $routeParams, $rootScope, naMidiaService) {
    $scope.offset = 0;
    $scope.limit = 10;
    $scope.naMidias = [];
    $scope.ultimasNaMidias = [];
    $scope.siteURL = window.location.href;
    if ($routeParams.naMidiaId != null) {
      $scope.listaPrincipalPromise = naMidiaService.obterNaMidia($routeParams.naMidiaId);
      $scope.listaPrincipalPromise.then(function(dataResponse) {
        $scope.naMidias[0] = dataResponse.data;
        $rootScope.pageTitle = $scope.naMidias[0].titulo;
        return $rootScope.pageDescription = $scope.naMidias[0].texto.replace(/<[^>]+>/gm, '').substring(0, 400) + "...";
      });
    } else {
      $scope.listaPrincipalPromise = naMidiaService.obterNaMidias($scope.limit, $scope.offset);
      $scope.listaPrincipalPromise.then(function(dataResponse) {
        $scope.naMidias = dataResponse.data;
        $rootScope.pageTitle = $scope.naMidias[0].titulo;
        return $rootScope.pageDescription = $scope.naMidias[0].texto.replace(/<[^>]+>/gm, '').substring(0, 400) + "...";
      });
    }
    $scope.noticiaLateralPromise = naMidiaService.obterNaMidias(15, 0);
    $scope.noticiaLateralPromise.then(function(dataResponse) {
      return $scope.ultimasNaMidias = dataResponse.data;
    });
    $scope.url = function(naMidia) {
      return naMidia.titulo.toLowerCase().replace(/\ /g, '-').replace(/[^\w-]+/g, "") + '/' + naMidia.id;
    };
    $scope.urltwitter = function(naMidia) {
      var title;
      title = '';
      if ($routeParams.naMidiaId == null) {
        title = "/" + naMidia.titulo.toLowerCase().replace(/\ /g, '-').replace(/[^\w-]+/g, "") + '/' + naMidia.id;
      }
      return "http://platform.twitter.com/widgets/tweet_button.ff7d9077a26377d36b6a53b1a95be617.en.html#_=1418920477717&count=horizontal&id=twitter-widget-0&lang=en&original_referer=" + encodeURIComponent(window.location.href) + "&size=m&text=@ceradvogados:&url=" + encodeURIComponent(window.location.href + title);
    };
    $scope.urlfacebook = function(naMidia) {
      var title;
      title = '';
      if ($routeParams.naMidiaId == null) {
        title = "/" + naMidia.titulo.toLowerCase().replace(/\ /g, '-').replace(/[^\w-]+/g, "") + '/' + naMidia.id;
      }
      return "http://www.facebook.com/plugins/like.php?href=" + encodeURIComponent(window.location.href + title) + "&layout=button_count&show_faces=false&width=90&action=like&font=verdana&colorscheme=light&locale=pt_BR";
    };
    $scope.urlgoogle = function(naMidia) {
      var title;
      title = '';
      if ($routeParams.naMidiaId == null) {
        title = "/" + naMidia.titulo.toLowerCase().replace(/\ /g, '-').replace(/[^\w-]+/g, "") + '/' + naMidia.id;
      }
      return "https://plusone.google.com/_/+1/fastbutton?bsv&size=medium&hl=en-US&url=" + window.location.href + title + "&parent=" + window.location.href;
    };
  });

  naMidiaApp.filter('htmlToPlaintext', function() {
    return function(text) {
      return String(text).replace(/<[^>]+>/gm, '');
    };
  });

  naMidiaApp.filter('resumir', function() {
    return function(text) {
      return String(text).substring(0, 400) + "...";
    };
  });

  naMidiaApp.config(function($sceProvider) {
    return $sceProvider.enabled(false);
  });

  naMidiaApp.config(function($routeProvider, $locationProvider) {
    $routeProvider.when('/na_midia', {
      templateUrl: 'na_midia_partial_listagem.html',
      controller: 'NaMidiaController'
    }).when('/na_midia/:title/:naMidiaId', {
      templateUrl: 'na_midia_partial_listagem.html',
      controller: 'NaMidiaController'
    }).otherwise({
      redirectTo: '/na_midia'
    });
    return $locationProvider.html5Mode(true);
  });

  naMidiaApp.value('cgBusyDefaults', {
    message: 'Carregando',
    backdrop: false,
    templateUrl: 'loader_template.html',
    delay: 500
  });

}).call(this);
