// Generated by CoffeeScript 1.8.0
(function() {
  var apiURL, segmentoApp;

  apiURL = 'http://api.servidor.adv.br/crsr/api/v.1';

  segmentoApp = angular.module('segmentoApp', ['ngSanitize', 'cgBusy']);

  segmentoApp.service('segmentoService', function($http) {
    delete $http.defaults.headers.common['X-Requested-With'];
    this.obterSegmentos = function(limit, offset) {
      return $http({
        method: 'GET',
        url: apiURL + '/segmento/?limit=' + limit + '&offset=' + offset
      });
    };
    this.obterSegmento = function(segmentoId) {
      return $http({
        method: 'GET',
        url: apiURL + '/segmento/' + segmentoId
      });
    };
  });

  segmentoApp.controller('SegmentoController', function($scope, segmentoService) {
    var idSegmentoBusca;
    $scope.offset = 0;
    $scope.limit = 10;
    $scope.segmento = null;
    $scope.entidadesClasseMenuCSS = "";
    $scope.candidatosCargoPublicoMenuCSS = "";
    $scope.servidoresAtivosMenuCSS = "";
    $scope.servidoresInativosMenuCSS = "";
    if (window.location.href.indexOf("entidade") !== -1) {
      idSegmentoBusca = 259715727;
      $scope.entidadesClasseMenuCSS = "active";
    } else if (window.location.href.indexOf("candidato") !== -1) {
      idSegmentoBusca = 259714562;
      $scope.candidatosCargoPublicoMenuCSS = "active";
    } else if (window.location.href.indexOf("ativo") !== -1) {
      idSegmentoBusca = 259584059;
      $scope.servidoresAtivosMenuCSS = "active";
    } else if (window.location.href.indexOf("inativo") !== -1) {
      idSegmentoBusca = 259715687;
      $scope.servidoresInativosMenuCSS = "active";
    }
    $scope.segmentoFindPromise = segmentoService.obterSegmento(idSegmentoBusca);
    $scope.segmentoFindPromise.then(function(dataResponse) {
      return $scope.segmento = dataResponse.data;
    });
  });

  segmentoApp.value('cgBusyDefaults', {
    message: 'Carregando',
    backdrop: false,
    templateUrl: 'loader_template.html',
    delay: 500
  });

}).call(this);
